
services:
  db:
    image: postgres:16-alpine
    container_name: todo_db_container
    environment:
      POSTGRES_USER: ${DB_USER}       
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env             
    ports:
      - "${DB_PORT}:5432"            
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  backend:
    container_name: todo_app_container
    build: ./backend                        
    ports:
      - "8080:8080"    
    restart: on-failure               
    env_file:
      - .env                         
    depends_on:
      - db                    
    volumes:
      - ./backend/uploads:/app/uploads  

  #frontend:
  #  container_name: todo_app_frontend
  #  build:
  #    context: ./frontend  # Apunta a la carpeta del frontend
  #  ports:
  #    # Expone el puerto 3000 de tu PC y lo mapea al puerto 80 de Nginx
  #    - "3000:80"
  #  depends_on:
  #    - backend

volumes:
  postgres_data: