
services:
  db:
    image: postgres:16-alpine
    container_name: todo_db_container
    environment:
      POSTGRES_USER: ${DB_USER}       
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env             
    ports:
      - "${DB_PORT}:5432"            
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: todo_app_container
    build: ./backend                        
    ports:
      - "8080:8080"    
    restart: on-failure               
    env_file:
      - .env                         
    depends_on:
      db:
        condition: service_healthy                   
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    container_name: todo_frontend_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped  
    
volumes:
  postgres_data: